# Generated by Django 2.2.1 on 2019-06-10 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samplenoteapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='noteap',
            new_name='noteapp',
        ),
    ]
